// Generated by dart2js, the Dart to JavaScript compiler.
$dart_deferred_initializers.current=function(S0) {
var A=S0.A
var B=S0.B
var C=S0.C
var D=S0.D
var E=S0.E
var F=S0.F
var G=S0.G
var H=S0.H
var J=S0.J
var K=S0.K
var L=S0.L
var M=S0.M
var N=S0.N
var O=S0.O
var P=S0.P
var Q=S0.Q
var R=S0.R
var S=S0.S
var T=S0.T
var U=S0.U
var V=S0.V
var W=S0.W
var X=S0.X
var Y=S0.Y
var Z=S0.Z
var init=S0.init
var setupProgram=S0.setupProgram
var I=S0.I
var $=I.p
var dart = [ ["","",,P,{
"^":"",
Qs:function(a,b,c,d,e,f,g){throw H.b(P.f("Process.start"))},
Fo:{
"^":"a;Q",
X:function(a){return C.MU.p(0,this.Q)}}}],["","",,U,{
"^":"",
P6:{
"^":"a;Q,ih:a<,b,c,d,e",
KP:[function(a){var z,y,x
z=P.p9("")
z.KF("graph molecule {")
z.KF("graph [dpi="+H.d(this.e)+" bgcolor=\""+H.d(this.c)+"\" truecolor=true];")
y=this.d
z.KF("edge [color=\""+H.d(y)+"\"];")
z.KF("node [fontcolor=\""+H.d(y)+"\" shape=plaintext];")
x=P.A(null,null)
a.gxp().aN(0,new U.Tx(this,a,z,x,P.A(null,null)))
y=a.gxp()
if(y.gor(y)){y=a.gxp()
J.kH(new U.I0(this,a).$1(y.gFV(y)),new U.nm(z,x))}z.KF("}")
return z.X(0)},"$1","gr8",2,0,54,4],
fC:function(a,b,c,d,e,f){this.Q.aN(0,new U.TF())},
static:{Hf:function(a,b,c,d,e,f){var z=new U.P6(e,b,f,a,d,c)
z.fC(a,b,c,d,e,f)
return z}}},
TF:{
"^":"r:55;",
$1:function(a){if(!J.mG(a.gHE(),1)&&!J.mG(a.gHE(),7))throw H.b(H.d(a.goc())+" is in main group "+H.d(a.gHE())+" and can thereforenot be sticky!")}},
Tx:{
"^":"r:36;Q,a,b,c,d",
$1:function(a){var z,y,x,w,v,u,t,s,r
z=this.Q
y=z.Q
if(y.tg(0,a.gFL()))return
x=a.gFL().gex()
w=this.d
if(!w.x4(x))J.C7(w,x,0)
v=H.d(x)
u=J.U(w)
t=J.WB(u.p(w,x),1)
u.q(w,x,t)
s=v+H.d(t)
this.c.q(0,a,s)
r=B.at(P.B([a.gFL(),1],null,null))
J.vo(J.C0(this.a.Tn(a),new U.vd()),y.gdj(y)).aN(0,r.ght(r))
z="label=<"+r.VV(0,z.a,!0,z.b)+">"
this.b.KF(s+" ["+C.Nm.zV([z]," ")+"];")}},
vd:{
"^":"r:3;",
$1:[function(a){return a.gFL()},null,null,2,0,null,5,"call"]},
I0:{
"^":"r:56;Q,a",
$2$pre:function(a,b){var z,y,x,w
z=[]
for(y=J.Nx(this.a.Tn(a));y.D();){x=y.gk()
if(J.mG(x,b))continue
w=this.$2$pre(x,a)
J.hV(J.qH(w,[],new U.bv()),0,a)
C.Nm.Ay(z,w)}if(C.Nm.gl0(z)&&!this.Q.Q.tg(0,a.gFL()))return[[a]]
return z},
$1:function(a){return this.$2$pre(a,null)}},
bv:{
"^":"r:12;",
$2:function(a,b){if(J.vU(J.wS(a),J.wS(b)))return a
return b}},
nm:{
"^":"r:57;Q,a",
$1:function(a){var z=this.Q
z.KF(J.XS(J.C0(a,new U.Xx(this.a))," -- "))
z.KF(";")}},
Xx:{
"^":"r:3;Q",
$1:[function(a){return this.Q.p(0,a)},null,null,2,0,null,6,"call"]}}],["","",,E,{
"^":"",
r4:{
"^":"bR;y,Q,a,b,c,d,e,f,r,x",
goc:function(){return"render"},
gN0:function(){return"Converts a structure formula to an image using Graph::Easy or Graphviz."},
r0:function(){var z,y
z=this.gZ6().p(0,"renderer")
y=[]
if(J.mG(this.gZ6().p(0,"format"),"txt")){y.push("--boxart")
z="graph-easy"}else y.push("-T"+H.d(this.gZ6().p(0,"format")))
return P.Qs(z,y,null,!0,C.cu,!1,null)},
dd:[function(a){var z=0,y=new P.S(),x=1,w,v=this
function dd(b,c){if(b===1){w=c
z=x}while(true)switch(z){case 0:z=2
return H.AZ(v.r0(),dd,y)
case 2:return H.AZ(null,0,y,null)
case 1:return H.AZ(w,1,y)}}return H.AZ(null,dd,y,null)},"$1","gbh",2,0,58,7],
bL:function(){var z=0,y=H.Gl(bL),x=2,w,v=[],u=this,t,s,r,q,p,o,n,m
function bL(a,b){if(a===1){w=b
z=x}while(true)switch(z){case 0:if(!J.mG(u.gZ6().p(0,"output"),"<stdout>"))P.aD(u.gZ6().p(0,"output")).hp()
else ;r=P.Ls(null,null,null,null)
if(u.gZ6().p(0,"no-sticky")!==!0)r.Ay(0,J.C0(u.gZ6().p(0,"sticky"),new E.zk()))
else ;q=!J.mG(u.gZ6().p(0,"format"),"txt")&&u.gZ6().p(0,"color")===!0
p=!J.mG(u.gZ6().p(0,"format"),"txt")&&u.gZ6().p(0,"subscript")===!0
o=u.gZ6().p(0,"bg")
n=u.gZ6().p(0,"fg")
m=U.Hf(o,q,P.QA(u.gZ6().p(0,"dpi"),null,null),n,r,p)
t=J.C0(J.C0(u.gJ9(),B.l7()),m.gr8())
p=P.Qw(J.C0(t,u.gbh()),null)
x=3
case 6:z=8
return H.Wm(p.D(),bL,y)
case 8:if(!(b===!0)){z=7
break}s=p.gk()
z=9
return H.Wm(s,bL,y)
case 9:z=6
break
case 7:v.push(5)
z=4
break
case 3:v=[2]
case 4:x=2
z=10
return H.Wm(p.Y(),bL,y)
case 10:z=v.pop()
break
case 5:case 1:return H.Wm(null,0,y)
case 2:return H.Wm(w,1,y)}}return H.hY(y)},
Zs:function(){var z=this.d
z.xJ("no-sticky",!1,"Disable the option below.",!1)
z.ye("sticky",!0,"H","Create no individual nodes for atoms for these types.",!0,"element,...")
z.uf("renderer","r",["dot","neato","twopi"],"neato","Name of the image rendering engine.\nIf `--format` is `txt` `graph-easy` will be used.","name")
z.P3("bg","transparent","Background color of the image.","color")
z.P3("fg","black","Foreground color of the image.","color")
z.P3("dpi","96","Dots per inch.","number")
z.pP("color",!0,"Colorize element symbols.")
z.pP("subscript",!0,"Print numbers in subscript.")
z.HA("format","f","txt","Target file format. (e.g. `png` or `jpg`)","type")
z.HA("output","o","<stdout>","Output directory.","path")
z.wZ("md5",["off","input","output"],"output","Use MD5 hash of input or output as file name.\nIf this options is turned `off` the files will be numbered consecutively.","mode")},
static:{ig:function(){var z=new E.r4(0,null,null,null,null,S.vG(null),null,P.L5(null,null,null,P.I,U.Y5),!0,C.xD)
z.wo()
z.Zs()
return z}}},
zk:{
"^":"r:3;",
$1:[function(a){return B.Rd(a)},null,null,2,0,null,8,"call"]}}],]
setupProgram(dart)
$=arguments[1]
C.MU=new H.kz([0,"ProcessStartMode.NORMAL",1,"ProcessStartMode.DETACHED",2,"ProcessStartMode.DETACHED_WITH_STDIO"])
C.cu=new P.Fo(0)
$.hp=null
}
$dart_deferred_initializers["XHTJE4nXwfWFMjdmR7xtiP6KbkY="]=$dart_deferred_initializers.current
