// Generated by dart2js, the Dart to JavaScript compiler.
$dart_deferred_initializers.current=function(S0) {
var A=S0.A
var B=S0.B
var C=S0.C
var D=S0.D
var E=S0.E
var F=S0.F
var G=S0.G
var H=S0.H
var J=S0.J
var K=S0.K
var L=S0.L
var M=S0.M
var N=S0.N
var O=S0.O
var P=S0.P
var Q=S0.Q
var R=S0.R
var S=S0.S
var T=S0.T
var U=S0.U
var V=S0.V
var W=S0.W
var X=S0.X
var Y=S0.Y
var Z=S0.Z
var init=S0.init
var setupProgram=S0.setupProgram
var I=S0.I
var $=I.p
var dart = [ ["","",,P,{
"^":"",
ZJ:function(a,b,c,d,e){var z,y,x,w,v,u,t
if(typeof c!=="number")return H.o(c)
z=J.rY(a)
y=!d
x=b
for(;x<c;){w=z.O2(a,x)
if(w===10)v=1
else if(w===13){u=x+1
if(u<c)v=z.O2(a,u)===10?2:1
else{if(y)return z.Nj(a,b,c)
v=1}}else v=0
if(v>0){e.$1(z.Nj(a,b,x))
x+=v
b=x}else ++x}if(x!==b){t=z.Nj(a,b,x)
if(d)e.$1(t)
else return t}return},
dI:{
"^":"zF;",
WJ:[function(a){var z=H.J([],[P.I])
P.ZJ(a,0,J.wS(a),!0,C.Nm.ght(z))
return z},"$1","gNN",2,0,51,0],
$aszF:function(){return[P.I,[P.zM,P.I]]}}}],["","",,P,{
"^":"",
Gi:function(a){if(a)return new P.RK(0,null)
else return new P.Ci(0,[])},
j3:function(a,b,c){var z=J.U(a)
switch(z.p(a,0)){case 1:return P.p(null)
case 2:return new P.O3(b,c,new P.Zz(z.p(a,2),z.p(a,1)))
case 3:return new P.O3("File closed",c,null)
default:return P.FM("Unknown error")}},
aD:function(a){if(typeof a!=="string")H.vh(P.p(H.d(P.hl(a))+" is not a String"))
return new P.Mn(a)},
qS:function(a){if(typeof a!=="string")H.vh(P.p(H.d(P.hl(a))+" is not a String"))
return new P.rT(a)},
c1:function(a){var z,y,x
if($.jL()){z=J.rY(a)
if(z.nC(a,$.XW())){y=z.XU(a,P.nu("[/\\\\]",!0,!1),2)
if(J.mG(y,-1))return a}else y=z.nC(a,"\\")||z.nC(a,"/")?0:-1}else y=J.co(a,"/")?0:-1
z=J.U(a)
x=z.cn(a,$.pP())
if(typeof y!=="number")return H.o(y)
if(x>y)return z.Nj(a,0,x+1)
else if(y>-1)return z.Nj(a,0,y+1)
else return"."},
y4:function(a,b){throw H.b(P.f("_IOService._dispatch"))},
lZ:function(){throw H.b(P.f("Platform._operatingSystem"))},
RB:function(){return P.lZ()},
RK:{
"^":"a;Q,a",
h:function(a,b){var z,y,x,w,v,u,t,s
z=J.U(b)
y=z.gv(b)
if(J.mG(y,0))return
x=this.Q
if(typeof y!=="number")return H.o(y)
w=x+y
x=this.a
if(x==null){x=H.vO(P.u(this.Rj(w),1024))
this.a=x}else if(x.length<w){v=H.vO(this.Rj(w)*2)
x=this.a
C.NA.vg(v,0,x.length,x)
this.a=v
x=v}if(!!z.$isn6)(x&&C.NA).vg(x,this.Q,w,b)
else for(u=0;u<y;++u){x=this.a
t=this.Q+u
s=z.p(b,u)
if(t>>>0!==t||t>=x.length)return H.e(x,t)
x[t]=s}this.Q=w},
OZ:function(){var z,y
z=this.a
if(z==null)return H.vO(0)
z=z.buffer
y=(z&&C.y7).Hq(z,0,this.Q)
this.Q=0
this.a=null
return y},
gv:function(a){return this.Q},
gl0:function(a){return this.Q===0},
gor:function(a){return this.Q!==0},
Rj:function(a){--a
a|=C.CD.wG(a,1)
a|=a>>>2
a|=a>>>4
a|=a>>>8
return((a|a>>>16)>>>0)+1},
p3:function(a){return this.gv(this).$0()}},
Ci:{
"^":"a;Q,a",
h:function(a,b){if(!J.t(b).$isn6)b=H.ht(H.XF(b))
this.a.push(b)
this.Q=this.Q+J.wS(b)},
OZ:function(){var z,y,x,w,v,u,t
z=this.a
y=z.length
if(y===0)return H.vO(0)
if(y===1){x=C.Nm.gV0(z)
this.Q=0
C.Nm.V1(z)
return x}x=H.vO(this.Q)
for(y=C.Nm.gu(z),w=0;y.D();){v=y.gk()
u=J.U(v)
t=u.gv(v)
if(typeof t!=="number")return H.o(t)
C.NA.vg(x,w,w+t,v)
u=u.gv(v)
if(typeof u!=="number")return H.o(u)
w+=u}this.Q=0
C.Nm.V1(z)
return x},
gv:function(a){return this.Q},
gl0:function(a){return this.Q===0},
gor:function(a){return this.Q!==0},
p3:function(a){return this.gv(this).$0()}},
Zz:{
"^":"a;G1:Q<,a",
X:function(a){var z,y,x
z=P.p9("")
z.KF("OS Error")
y=this.Q
if(J.FN(y)!==!0){z.KF(": ")
z.KF(y)
y=this.a
x=J.t(y)
if(!x.m(y,-1)){z.KF(", errno = ")
z.KF(x.X(y))}}else{y=this.a
x=J.t(y)
if(!x.m(y,-1)){z.KF(": errno = ")
z.KF(x.X(y))}}return z.X(0)}},
Mn:{
"^":"xG;Q",
N9:function(){P.BN(this.Q)},
z9:function(a){var z,y
if(a){this.N9()
z=this.Q
y=P.c1(z)
if(typeof y!=="string")H.vh(P.p(H.d(P.hl(y))+" is not a String"))
if(!J.mG(z,y)){z=P.c1(z)
if(typeof z!=="string")H.vh(P.p(H.d(P.hl(z))+" is not a String"))
new P.Mn(z).z9(!0)}}P.Wl(this.Q)},
hp:function(){return this.z9(!1)},
X:function(a){return"Directory: '"+H.d(this.Q)+"'"},
static:{BN:function(a){throw H.b(P.f("Directory._exists"))},Wl:function(a){throw H.b(P.f("Directory._create"))}}},
fH:{
"^":"a;Q"},
c2:{
"^":"a;"},
O3:{
"^":"a;G1:Q<,a,b",
X:function(a){var z,y
z=P.p9("")
z.KF("FileSystemException")
y=this.Q
if(!C.xB.gl0(y)){z.KF(": "+y)
y=this.a
if(y!=null)z.KF(", path = '"+H.d(y)+"'")
y=this.b
if(y!=null)z.KF(" ("+J.L(y)+")")}else{y=this.b
if(y!=null){z.KF(": "+J.L(y))
y=this.a
if(y!=null)z.KF(", path = '"+H.d(y)+"'")}else{y=this.a
if(y!=null)z.KF(": "+H.d(y))}}return z.X(0)},
static:{PY:function(a,b,c){return new P.O3(a,b,c)}}},
rT:{
"^":"xG;Q",
Q7:function(a){if(a!==C.yo&&a!==C.f5&&a!==C.E2)return P.Xo(P.p(null),null,null)
return P.y4(5,[this.Q,a.Q]).ml(new P.Ph(this))},
Sb:function(){return this.Q7(C.yo)},
p3:[function(a){return P.y4(12,[this.Q]).ml(new P.uv(this))},"$0","gv",0,0,52],
II:function(){return this.Sb().ml(new P.OP(new P.xK()))},
Lm:function(a,b){var z,y
try{z=b.kV(a)
return z}catch(y){H.R(y)
throw H.b(P.PY("Failed to decode data using encoding '"+b.goc()+"'",this.Q,null))}},
QA:function(a){return this.II().ml(new P.nB(this,a))},
YL:function(a){return this.QA(a).ml(C.Nb.gNN())},
iR:function(){return this.YL(C.Mb)},
X:function(a){return"File: '"+H.d(this.Q)+"'"}},
Ph:{
"^":"r:3;Q",
$1:function(a){a.p(0,0)
throw H.b(P.j3(a,"Cannot open file",this.Q.Q))}},
uv:{
"^":"r:3;Q",
$1:function(a){a.p(0,0)
throw H.b(P.j3(a,"Cannot retrieve length of file",this.Q.Q))}},
xK:{
"^":"r:53;",
$1:function(a){var z,y
z=P.Gi(!1)
y=P.S(null)
new P.dm(a,z,y).$0()
return y.Q}},
dm:{
"^":"r:2;Q,a,b",
$0:function(){var z=this.b
this.Q.OF(65536).Rx(new P.u7(this.a,z,this),z.gYJ())}},
u7:{
"^":"r:3;Q,a,b",
$1:[function(a){var z=J.U(a)
if(J.vU(z.gv(a),0))this.Q.h(0,a)
if(J.mG(z.gv(a),65536))this.b.$0()
else this.a.aM(this.Q.OZ())},null,null,2,0,null,0,"call"]},
OP:{
"^":"r:3;Q",
$1:[function(a){return J.kQ(a).ml(new P.Yu(this.Q,a)).wM(a.gJK())},null,null,2,0,null,1,"call"]},
Yu:{
"^":"r:3;Q,a",
$1:[function(a){if(J.mG(a,0))return this.Q.$1(this.a)
return this.a.OF(a)},null,null,2,0,null,2,"call"]},
nB:{
"^":"r:3;Q,a",
$1:[function(a){return this.Q.Lm(a,this.a)},null,null,2,0,null,3,"call"]},
xG:{
"^":"a;"}}],["","",,H,{
"^":"",
XF:function(a){var z,y,x,w,v
z=J.t(a)
if(!!z.$isDD)return a
y=z.gv(a)
if(typeof y!=="number")return H.o(y)
x=Array(y)
x.fixed$length=Array
y=x.length
w=0
while(!0){v=z.gv(a)
if(typeof v!=="number")return H.o(v)
if(!(w<v))break
v=z.p(a,w)
if(w>=y)return H.e(x,w)
x[w]=v;++w}return x}}],]
setupProgram(dart)
$=arguments[1]
C.Nb=new P.dI()
C.yo=new P.fH(0)
C.f5=new P.fH(1)
C.E2=new P.fH(2)
$.lL=1
}
$dart_deferred_initializers["SgA8GkeMvqd2L1LM3MDm81HqM0E="]=$dart_deferred_initializers.current
