// Generated by dart2js, the Dart to JavaScript compiler.
$dart_deferred_initializers.current=function(S0) {
var A=S0.A
var B=S0.B
var C=S0.C
var D=S0.D
var E=S0.E
var F=S0.F
var G=S0.G
var H=S0.H
var J=S0.J
var K=S0.K
var L=S0.L
var M=S0.M
var N=S0.N
var O=S0.O
var P=S0.P
var Q=S0.Q
var R=S0.R
var S=S0.S
var T=S0.T
var U=S0.U
var V=S0.V
var W=S0.W
var X=S0.X
var Y=S0.Y
var Z=S0.Z
var init=S0.init
var setupProgram=S0.setupProgram
var I=S0.I
var $=I.p
var dart = [ ["","",,P,{
"^":"",
v8:function(){$.LF=P.as()
return $.LF},
as:function(){throw H.b(P.f("StdIOUtils._getStdioInputStream"))}}],]
setupProgram(dart)
$=arguments[1]
$.LF=null
}
$dart_deferred_initializers["IAwMMpAjE7H+nh0cBEsb8c2c2+s="]=$dart_deferred_initializers.current
